### ISSUE TITLE
[Screen video] I rewrote the installation script, what do you think?

### ISSUE THREAD

**Issue by qexat** [Blyxyas/simple-workspaces#1]
As you might have seen, I forked this repository.
Tonight, I started playing with it and rewrote the install script to make it look fancy :sparkles: 

Here is a small video snippet, hope you like it :)
[Screencast from 25-09-2022 22:36:21.webm](https://user-images.githubusercontent.com/43090614/192164621-b1d3ec33-6617-4f02-9549-763dba073ae8.webm)

FYI: the aesthetics are inspired from `pacman` (and more specifically `yay`)

**Comment by qexat** [comment]
btw, normally it would ask for a password right after the message "needs to be run as root" but I already executed it before xd

**Comment by blyxyas** [comment]
wow really fancy ✨ aesthetics ✨, but I didn't remembered this thing until the issue was open
if you want, I'll  merge it.

I posted this to Reddit one day and the backlash was so bad that I just forgot about it.
but thanks for improving in this!

**Comment by qexat** [comment]
> wow really fancy ✨ aesthetics ✨, but I didn't remembered this thing until the issue was open
> 
> if you want, I'll  merge it.
> 
> 
> 
> I posted this to Reddit one day and the backlash was so bad that I just forgot about it.
> 
> but thanks for improving in this!

oh sad :( well I'll just try to improve it for fun, don't expect a PR soon haha
